name: CICD

on:
  workflow_call:
    secrets:
      AZURE_CREDENTIALS:
        required: true
      AZURE_WEBAPP_NAME:
        required: true


jobs:
  build-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Gradle
      run: gradle build
      
    - name: Get app version
      id: get-version
      run: echo "::set-output name=app_version::`gradle properties -q | grep '^version:' | awk '{print $2}'`"

    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        package: build/libs/*-${{ steps.get-version.outputs.app_version }}.jar

    # Azure logout 
    - name: logout
      run: |
        az logout